# Generated by Django 3.0.1 on 2020-02-09 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='house',
            name='area',
            field=models.IntegerField(),
        ),
    ]
